version: "3.7"
services:
  test_task_worker:
    container_name: test_task_worker
    build:
      context: notification-worker/.
      dockerfile: Dockerfile
    image: test_task_worker
    restart: unless-stopped
    depends_on:
      - test_rabbitmq
    links:
      - test_rabbitmq:test_rabbitmq
    networks:
      - tesk_task_network


  test_rabbitmq:
    image: rabbitmq:3-management
    container_name: test_rabbitmq
    volumes:
      - /var/lib/rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    env_file:
      - ./rabbitmq.env
    networks:
      - tesk_task_network


networks:
  tesk_task_network:
